# Use lld linker on Linux and Windows for faster linking
# macOS doesn't support lld.
[target.x86_64-unknown-linux-gnu]
linker = "rust-lld"

[target.aarch64-unknown-linux-gnu]
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld"

[env]
TS_RS_EXPORT_DIR = { value = "src/types/generated", relative = true }
# workaround needed to prevent `STATUS_ENTRYPOINT_NOT_FOUND` error in tests
# see https://github.com/tauri-apps/tauri/pull/4383#issuecomment-1212221864
__TAURI_WORKSPACE__ = "true"